### ISSUE TITLE
Some suggestions for the people to visit

### ISSUE THREAD

**Issue by yangninghua** [ducha-aiki/affnet#25]
torch-0.4.1-cp27-cp27mu-manylinux1_x86_64.whl
numpy-1.16.4-cp27-cp27m-manylinux1_x86_64.whl
torchvision-0.2.1-py2.py3-none-any.whl
pip install matplotlib -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install seaborn -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install tqdm -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by yangninghua** [comment]
```
if you have GTX 2080ti

python -mpip install torch==1.0.1 -f https://download.pytorch.org/whl/cu100/stable

or

wget https://download.pytorch.org/whl/cu100/torch-1.0.1-cp36-cp36m-linux_x86_64.whl
python -mpip install torch-1.0.1-cp36-cp36m-linux_x86_64.whl
```

**Comment by yangninghua** [comment]
GTX 2080ti

**Comment by yangninghua** [comment]
```
Test epoch 11
Test on graf1-6, 177 tentatives 10 true matches 0.056  inl.ratio
Now native ori
(0.05713510513305664, 'detection multiscale')
('affnet_time', 0.020704984664916992)
('pe_time', 0.08408308029174805)
(0.15633296966552734, 'affine shape iters')
(0.17961907386779785, 'detection multiscale')
('affnet_time', 0.02036309242248535)
('pe_time', 0.0667581558227539)
(0.13908100128173828, 'affine shape iters')
Test epoch 11
Test on ori graf1-6, 133 tentatives 5 true matches 0.037  inl.ratio
Traceback (most recent call last):
  File "/home/apple/code/affnet-master/train_AffNet_test_on_graffity.py", line 416, in <module>
    main(train_loader, test_loader, model)
  File "/home/apple/code/affnet-master/train_AffNet_test_on_graffity.py", line 380, in main
    train(train_loader, model, optimizer1, epoch)
  File "/home/apple/code/affnet-master/train_AffNet_test_on_graffity.py", line 192, in train
    pbar = tqdm(enumerate(train_loader))
  File "/home/apple/.conda/envs/py2_7-pytorch0_4_1/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "/home/apple/.conda/envs/py2_7-pytorch0_4_1/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 289, in __init__
    w.start()
  File "/home/apple/.conda/envs/py2_7-pytorch0_4_1/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/home/apple/.conda/envs/py2_7-pytorch0_4_1/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

```
parser.add_argument('--num-workers', default= 8,
                    help='Number of workers to be created')

default= 0 or default= 1
.............
.............
.............
def create_loaders():

    kwargs = {'num_workers': args.num_workers, 'pin_memory': args.pin_memory} if args.cuda else {}
```

**Comment by yangninghua** [comment]
```
--gpu-id=0 --dataroot=dataset/6Brown --num-workers=0 --pin-memory=False --lr=0.005 --n-pairs=100 --n-test-pairs=100 --batch-size=8 --test-batch-size=8 --descriptor=HardNet --arch=AffNetFast --loss=HardNegC --epochs=20 --expname=AffNetFast_lr005_10M_20ep_aswap
```
